In [1]:
import numpy as np
import pandas as pd
import pipeline
import matplotlib.pyplot as plt
from pydmd import DMD
from jupyterthemes import jtplot ; jtplot.style()
from os import chdir ; chdir('/Users/albertwakhloo/Desktop/theoretical_neuroscience/neuromatch/steinmetz full/allData/all dat')
from glob import glob

In [2]:
f = glob('*')
basal_ganglia = np.array(["ACB", "CP", "GPe", "LS", "LSc", "LSr", "MS", "OT", "SNr", "SI"])
paths = pipeline.filt(f, regions_to_pull = basal_ganglia)
paths.head(5)

Origin                abbrev  n_relevant_probes
0       Cori_2016-12-14       Cori_2016-12-14                1.0
1      Moniz_2017-05-16      Moniz_2017-05-16                0.0
2     Muller_2017-01-09     Muller_2017-01-09                0.0
3  Lederberg_2017-12-08  Lederberg_2017-12-08                1.0
4   Richards_2017-11-02   Richards_2017-11-02                0.0

In [7]:
subset = paths[paths.n_relevant_probes >= 2].Origin.values
spikes, stim, neur = pipeline.pipeline(subset)

Getting spike time data ...
Hench_2017-06-18
Mapping neurons from Hench_2017-06-18 to channels ... 
Mapping channels to brain areas ...
Getting behavioral data ...
~~~ OOOoOOOOooOoOOOOOOOOOOoooOooOOOOOOo ~~~
Forming groups ... 
Forming spike trains ...
Forming stimulus series ...
Creating data-frame ...
~~~ the power of christ literally compels you ~~~
Getting spike time data ...
Richards_2017-11-01
Mapping neurons from Richards_2017-11-01 to channels ... 
Mapping channels to brain areas ...
Getting behavioral data ...
~~~ OOOoOOOOooOoOOOOOOOOOOoooOooOOOOOOo ~~~
Forming groups ... 
Forming spike trains ...
Forming stimulus series ...
Creating data-frame ...
~~~ the power of christ literally compels you ~~~
Getting spike time data ...
Lederberg_2017-12-11
Mapping neurons from Lederberg_2017-12-11 to channels ... 
Mapping channels to brain areas ...
Getting behavioral data ...
~~~ OOOoOOOOooOoOOOOOOOOOOoooOooOOOOOOo ~~~
Forming groups ... 
Forming spike trains ...
Forming stimulus series

drop neuron columns which weren't measured and make a df out of each mouse

In [12]:
mice = [spikes[spikes.maus == mouse].dropna(axis = 1) for mouse in spikes.maus.unique()]
mice_spikes = [mouse.iloc[:, -6] for mouse in mice] #you gotta start pulling out pure spikes mango... set this in pipeline soon

In [26]:
dmd = DMD(svd_rank = 2)

In [37]:
d1 = dmd.fit(mice_spikes[0].T)

In [44]:
l = d1.reconstructed_data[0]

In [45]:
l[l!=0]

array([nan])

In [35]:
m1 =mice_spikes[0]

In [49]:
stim_avg = pipeline.extract_trial_stim_avg(neur, stim, basal_ganglia)

Generating mouse 0 spike rate data ...
Generating mouse 1 spike rate data ...
Generating mouse 2 spike rate data ...
Generating mouse 3 spike rate data ...
~~~ young success ~~~~


In [50]:
stim_avg

LSc        CP  LSr  maus  SNr  SI  ACB  OT  GPe
0    2.633929  2.193764  3.6     0  NaN NaN  NaN NaN  NaN
1    1.875000  2.048998  2.0     0  NaN NaN  NaN NaN  NaN
2    0.892857  2.004454  3.2     0  NaN NaN  NaN NaN  NaN
3    2.008929  2.416481  3.8     0  NaN NaN  NaN NaN  NaN
4    1.383929  1.302895  2.4     0  NaN NaN  NaN NaN  NaN
..        ...       ...  ...   ...  ...  ..  ...  ..  ...
524  1.160714  1.648107  1.6     0  NaN NaN  NaN NaN  NaN
525  1.785714  1.046771  1.6     0  NaN NaN  NaN NaN  NaN
526  0.401786  1.291759  0.6     0  NaN NaN  NaN NaN  NaN
527  1.026786  2.060134  1.8     0  NaN NaN  NaN NaN  NaN
528  1.339286  2.048998  0.6     0  NaN NaN  NaN NaN  NaN

[529 rows x 9 columns]

In [94]:
dmd = DMD(svd_rank = 1)
maus_1 = stim_avg[stim_avg.maus == 0].dropna(axis = 1).drop('maus', axis = 1).values.T
d = dmd.fit(maus_1)

In [95]:
d.reconstructed_data.shape

(3, 529)

In [99]:
np.cov(maus_1)

array([[0.27144192, 0.11793966, 0.13501664],
       [0.11793966, 0.43167977, 0.14374446],
       [0.13501664, 0.14374446, 0.72194936]])

In [86]:
maus_1.values

array([[2.63392857, 2.19376392, 3.6       ],
       [1.875     , 2.04899777, 2.        ],
       [0.89285714, 2.00445434, 3.2       ],
       ...,
       [0.40178571, 1.29175947, 0.6       ],
       [1.02678571, 2.06013363, 1.8       ],
       [1.33928571, 2.04899777, 0.6       ]])

In [101]:
maus_1.shape

(3, 529)